///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ItemModelDataItemCategoryStoreAreaCity {
/*
{
  "id": 2,
  "name": "Mahala"
}
*/

  int? id;
  String? name;

  ItemModelDataItemCategoryStoreAreaCity({
    this.id,
    this.name,
  });
  ItemModelDataItemCategoryStoreAreaCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ItemModelDataItemCategoryStoreArea {
/*
{
  "id": 2,
  "name": "Mashhama",
  "city": {
    "id": 2,
    "name": "Mahala"
  }
}
*/

  int? id;
  String? name;
  ItemModelDataItemCategoryStoreAreaCity? city;

  ItemModelDataItemCategoryStoreArea({
    this.id,
    this.name,
    this.city,
  });
  ItemModelDataItemCategoryStoreArea.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    city = (json['city'] != null)
        ? ItemModelDataItemCategoryStoreAreaCity.fromJson(json['city'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (city != null) {
      data['city'] = city!.toJson();
    }
    return data;
  }
}

class ItemModelDataItemCategoryStore {
/*
{
  "id": 1,
  "name": "Pizza Burger",
  "description": "pizza",
  "image": "http://www.inoutdesigners.com/talabat/public/upload/store/1635185415download (1).jpeg",
  "rate": "0.00",
  "reviews_number": 0,
  "open_at": "08:00:00",
  "close_at": "14:03:00",
  "delivery_fees": 10,
  "taxes": 0,
  "area": {
    "id": 2,
    "name": "Mashhama",
    "city": {
      "id": 2,
      "name": "Mahala"
    }
  }
}
*/

  int? id;
  String? name;
  String? description;
  String? image;
  String? rate;
  int? reviewsNumber;
  String? openAt;
  String? closeAt;
  int? deliveryFees;
  int? taxes;
  ItemModelDataItemCategoryStoreArea? area;

  ItemModelDataItemCategoryStore({
    this.id,
    this.name,
    this.description,
    this.image,
    this.rate,
    this.reviewsNumber,
    this.openAt,
    this.closeAt,
    this.deliveryFees,
    this.taxes,
    this.area,
  });
  ItemModelDataItemCategoryStore.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    image = json['image']?.toString();
    rate = json['rate']?.toString();
    reviewsNumber = json['reviews_number']?.toInt();
    openAt = json['open_at']?.toString();
    closeAt = json['close_at']?.toString();
    deliveryFees = json['delivery_fees']?.toInt();
    taxes = json['taxes']?.toInt();
    area = (json['area'] != null)
        ? ItemModelDataItemCategoryStoreArea.fromJson(json['area'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['image'] = image;
    data['rate'] = rate;
    data['reviews_number'] = reviewsNumber;
    data['open_at'] = openAt;
    data['close_at'] = closeAt;
    data['delivery_fees'] = deliveryFees;
    data['taxes'] = taxes;
    if (area != null) {
      data['area'] = area!.toJson();
    }
    return data;
  }
}

class ItemModelDataItemCategory {
/*
{
  "id": 2,
  "name": "pizza2",
  "image": "http://via.placeholder.com/200x200?text=No+Image",
  "store": {
    "id": 1,
    "name": "Pizza Burger",
    "description": "pizza",
    "image": "http://www.inoutdesigners.com/talabat/public/upload/store/1635185415download (1).jpeg",
    "rate": "0.00",
    "reviews_number": 0,
    "open_at": "08:00:00",
    "close_at": "14:03:00",
    "delivery_fees": 10,
    "taxes": 0,
    "area": {
      "id": 2,
      "name": "Mashhama",
      "city": {
        "id": 2,
        "name": "Mahala"
      }
    }
  }
}
*/

  int? id;
  String? name;
  String? image;
  ItemModelDataItemCategoryStore? store;

  ItemModelDataItemCategory({
    this.id,
    this.name,
    this.image,
    this.store,
  });
  ItemModelDataItemCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    store = (json['store'] != null)
        ? ItemModelDataItemCategoryStore.fromJson(json['store'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    if (store != null) {
      data['store'] = store!.toJson();
    }
    return data;
  }
}

class ItemModelDataExtras {
/*
{
  "id": 1,
  "name": "Onion",
  "price": 10
}
*/

  int? id;
  String? name;
  int? price;

  ItemModelDataExtras({
    this.id,
    this.name,
    this.price,
  });
  ItemModelDataExtras.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    price = json['price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['price'] = price;
    return data;
  }
}

class ItemModelDataSizes {
/*
{
  "id": 2,
  "name": "44",
  "price": 44
}
*/

  int? id;
  String? name;
  int? price;

  ItemModelDataSizes({
    this.id,
    this.name,
    this.price,
  });
  ItemModelDataSizes.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    price = json['price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['price'] = price;
    return data;
  }
}

class ItemModelData {
  int? id;
  String? name;
  String? description;
  String? image;
  int? numOrders;
  List<ItemModelDataSizes?>? sizes;
  List<ItemModelDataExtras?>? extras;
  ItemModelDataItemCategory? itemCategory;

  ItemModelData({
    this.id,
    this.name,
    this.description,
    this.image,
    this.numOrders,
    this.sizes,
    this.extras,
    this.itemCategory,
  });
  ItemModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    image = json['image']?.toString();
    numOrders = json['num_orders']?.toInt();
    if (json['sizes'] != null) {
      final v = json['sizes'];
      final arr0 = <ItemModelDataSizes>[];
      v.forEach((v) {
        arr0.add(ItemModelDataSizes.fromJson(v));
      });
      sizes = arr0;
    }
    if (json['extras'] != null) {
      final v = json['extras'];
      final arr0 = <ItemModelDataExtras>[];
      v.forEach((v) {
        arr0.add(ItemModelDataExtras.fromJson(v));
      });
      extras = arr0;
    }
    itemCategory = (json['item_category'] != null)
        ? ItemModelDataItemCategory.fromJson(json['item_category'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['image'] = image;
    data['num_orders'] = numOrders;
    if (sizes != null) {
      final v = sizes;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['sizes'] = arr0;
    }
    if (extras != null) {
      final v = extras;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['extras'] = arr0;
    }
    if (itemCategory != null) {
      data['item_category'] = itemCategory!.toJson();
    }
    return data;
  }
}

class ItemModel {
/*
{
  "status": 1,
  "message": "success",
  "data": {
    "id": 3,
    "name": "Margreta",
    "description": "pizza",
    "image": "http://www.inoutdesigners.com/talabat/public/upload/item/1635277552download (1).jpeg",
    "num_orders": 0,
    "sizes": [
      {
        "id": 2,
        "name": "44",
        "price": 44
      }
    ],
    "extras": [
      {
        "id": 1,
        "name": "Onion",
        "price": 10
      }
    ],
    "item_category": {
      "id": 2,
      "name": "pizza2",
      "image": "http://via.placeholder.com/200x200?text=No+Image",
      "store": {
        "id": 1,
        "name": "Pizza Burger",
        "description": "pizza",
        "image": "http://www.inoutdesigners.com/talabat/public/upload/store/1635185415download (1).jpeg",
        "rate": "0.00",
        "reviews_number": 0,
        "open_at": "08:00:00",
        "close_at": "14:03:00",
        "delivery_fees": 10,
        "taxes": 0,
        "area": {
          "id": 2,
          "name": "Mashhama",
          "city": {
            "id": 2,
            "name": "Mahala"
          }
        }
      }
    }
  }
}
*/

  int? status;
  String? message;
  ItemModelData? data;

  ItemModel({
    this.status,
    this.message,
    this.data,
  });
  ItemModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ItemModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
